name: Kali SM7325 Release

on: [workflow_dispatch]

jobs:
  build:
    name: Build Image(s)
    permissions: write-all
    runs-on: ubuntu-latest
    # timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4

      - name: Clone Repository
        run: |
          sudo apt update
          sudo apt install -y debootstrap systemd-container rsync qemu-user-static bmap-tools android-sdk-libsparse-utils
          git clone https://github.com/Shubhamvis98/kali-pinephone build
          cp custom.sh build

      - name: Download base.tgz
        run: |
          bash base.url

      - name: Build
        run: |
          cd build
          chmod +x build.sh
          sudo bash -e ./build.sh -c -t sm7325 -s custom.sh
          sha1sum *.img* > sha1sum

      - uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          if-no-files-found: warn
          retention-days: 7
          path: |
            build/*.img*
            build/sha1sum

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Custom Variables
        id: vars
        run: |
          echo "date=SM7325-$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "repository=shubhamvis98/kali-pinephone" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts

      - name: List Files
        run: |
          ls -lh

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}
          repository: ${{ steps.vars.outputs.repository }}
          tag_name: ${{ steps.vars.outputs.date }}
          name: SM7325 Release ${{ steps.vars.outputs.date }}
          files: |
            *.img*
            sha1sum
          body: |
            **Default User/Pass:** kali/8888

            ### Installation:

            **Supported Devices:**
            - Nothing Phone(1) (spacewar)

            ### Install on EMMC:
            ```
            tar -xpf kali_phosh_{SOC}_{DATE}.tar.xz
            fastboot flash userdata kali_phosh_{SOC}_{DATE}.img
            fastboot flash boot boot-{model}.img
            ```
            ### WARNING: This will wipe your phone. So, I won't recommend to flash it in your daily driver, but if your device supports external sdcard, go ahead (-;

            #### Create an issue if you see any bug in the release
            ### [If you find my work useful and would like to support it, consider making a donation](https://fossfrog.in/donate/)

            ![GitHub release (by tag)](https://img.shields.io/github/downloads/${{ steps.vars.outputs.repository }}/${{ steps.vars.outputs.date }}/total?label=Downloads)
