name: Kali SM7325 Release

on: [workflow_dispatch]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    # timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4

      - name: Set Custom Variables
        id: vars
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "repository=shubhamvis98/kali-pinephone" >> $GITHUB_OUTPUT

### Build Code Starts from Here

      - name: Clone Repository
        run: |
          sudo apt update
          sudo apt install -y debootstrap systemd-container rsync qemu-user-static bmap-tools android-sdk-libsparse-utils
          git clone https://github.com/Shubhamvis98/kali-pinephone -b wip build
          cp custom.sh build
          cd build
          #patch -p1 < ../my.patch

      - name: Download base.tgz
        run: |
          pip install gdown
          gdown --fuzzy 'https://drive.google.com/file/d/1-jYrR55zzr0K0YCTaZ0tU4OM_sW2yYkF/view?usp=sharing' -O build/base.tgz

      - name: Build
        run: |
          cd build
          chmod +x build.sh
          sudo ./build.sh -t sm7325 -s custom.sh
          sudo xz kali_phosh*img
          sha1sum *.img* > sha1sum

### Build Code Ends Here

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}
          repository: ${{ steps.vars.outputs.repository }}
          tag_name: ${{ steps.vars.outputs.date }}
          name: SDM845 Release ${{ steps.vars.outputs.date }}
          files: |
            build/*.img*
            build/sha1sum
          body: |
            **Default User/Pass:** kali/8888

            ### Installation:

            **Supported Devices:**
            - Nothing Phone(1) (spacewar)

            ### Install on EMMC:
            ```
            tar -xpf kali_phosh_SOC_YYYYMMDD.tar.xz
            simg2img kali_phosh_SOC_YYYYMMDD.img rootfs_ext4.img
            fastboot flash userdata kali_phosh_SOC_YYYYMMDD.img
            fastboot flash boot boot-{model}.img
            ```

            ### WARNING: This will wipe your phone. So, I won't recommend to flash it in your daily driver, but if your device supports external sdcard, go ahead (-;

            #### Create an issue if you see any bug in the release
            ### [If you find my work useful and would like to support it, consider making a donation](https://fossfrog.in/donate/)

            ![GitHub release (by tag)](https://img.shields.io/github/downloads/${{ steps.vars.outputs.repository }}/${{ steps.vars.outputs.date }}/total?label=Downloads)
