name: Kali PinePhone/Pro Release Test

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling
    # timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4

      - name: Set Custom Variables
        id: vars
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "repository=shubhamvis98/Runner" >> $GITHUB_OUTPUT

### Build Code Starts from Here

      - name: Clone Repository
        run: |
          apt update
          apt install -y sudo git fdisk debootstrap systemd-container rsync qemu-user-static bmap-tools
          git clone -b 20240331 https://github.com/Shubhamvis98/kali-pinephone build
          cp custom.sh build
          LOOP=`losetup -f | awk '{print $1}'`
          sudo rm $LOOP || echo
          mknod $LOOP b 7 11

      - name: Build
        run: |
          cd build
          chmod +x build.sh
          sudo ./build.sh -cb -t pinephone -s custom.sh
          #sudo ./build.sh -cb -t pinephonepro -s custom.sh
          for i in *.img.xz; do sha1sum ${i} > ${i}.sha1; done

### Build Code Ends Here

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          generate_release_notes: false
          prerelease: false
          tag_name: ${{ steps.vars.outputs.date }}
          name: Release ${{ steps.vars.outputs.date }}
          files: build/*.img*
          token: ${{ secrets.RELEASE_TOKEN }}
          repository: ${{ steps.vars.outputs.repository }}
          body: |
            **Default User/Pass:** kali/8888

            ### Installation:

            #### From PinePhone/Pro:
            ```
            unxz ${IMAGE_FILE}.xz && bmaptool copy ${IMAGE_FILE} /dev/mmcblkX
            or
            unxz -c ${IMAGE_FILE}.xz | dd of=/dev/mmcblkX bs=1M oflag=sync status=progress
            X: Storage Device
            ```

            #### From PC [Use Tow-Boot's Mass Storage]:
            While booting press Vol-up to boot into Mass Storage, led color will be blue
            ```
            unxz ${IMAGE_FILE}.xz && bmaptool copy ${IMAGE_FILE} /dev/sdX
            or
            unxz -c ${IMAGE_FILE}.xz | dd of=/dev/sdX bs=1M oflag=sync status=progress
            X: Storage Device
            ```

            #### Please install Tow-Boot if boot fails
            #### Create an issue if you see any bug in the release
            ![GitHub release (by tag)](https://img.shields.io/github/downloads/${{ steps.vars.outputs.repository }}/${{ steps.vars.outputs.date }}/total?label=Downloads)
